version: "3.8"

services:
  remix:
    image: ${DOCKER_USERNAME}/getdoa-remix:latest
    platform: linux/arm64
    ports:
      - "REMIX_PORT"
    environment:
      DATABASE_URL: file:/sqlite/dev.db
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    volumes:
      - sqlite_data:/sqlite

  volumes:
    sqlite_data:
      driver: local
