version: "3.8"

services:
  remix:
    image: ${DOCKER_USERNAME}/getdoa-remix:latest
    ports:
      - "${PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - app-network

  db:
    image: arm64v8/postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s # Added to ensure initial startup time is given

volumes:
  db_data:

networks:
  app-network:
