name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Remix service
      - name: Build and push Remix Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./remix
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/getdoa-remix:latest
          build-args: |
            DATABASE_URL=file:/sqlite/dev.db
