name: Deploy to EC2 via SSM

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application with docker-compose and environment file" \
            --parameters '{"commands": [
              "echo \"DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}\" > /home/ubuntu/.env",
              "echo \"POSTGRES_USER=${{ secrets.POSTGRES_USER }}\" >> /home/ubuntu/.env",
              "echo \"POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\" >> /home/ubuntu/.env",
              "echo \"POSTGRES_DB=${{ secrets.POSTGRES_DB }}\" >> /home/ubuntu/.env",
              "echo \"SESSION_SECRET=${{ secrets.SESSION_SECRET }}\" >> /home/ubuntu/.env",

              "cd /home/ubuntu",

              "sudo docker-compose --env-file /home/ubuntu/.env pull",

              "sudo docker-compose --env-file /home/ubuntu/.env restart"
            ]}'
