name: Deploy to EC2 via SSM

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application with docker-compose and injected environment variables" \
            --parameters '{"commands": [
                "set -e",

                "WORKDIR=/home/ubuntu/deployment",
                "BLUE_DIR=$WORKDIR/blue",
                "GREEN_DIR=$WORKDIR/green",
                "CURRENT_DIR=$(docker ps --filter name=my-app --format \"{{.Names}}\")",
                "NEXT_DIR=$([ \"$CURRENT_DIR\" == \"$BLUE_DIR\" ] && echo \"$GREEN_DIR\" || echo \"$BLUE_DIR\")",

                "mkdir -p $NEXT_DIR",
                
                "curl -o $NEXT_DIR/docker-compose.yaml https://raw.githubusercontent.com/Hazqeel09/getdoav3/refs/heads/main/docker-compose.yaml",

                "docker-compose -f $NEXT_DIR/docker-compose.yaml pull",

                "docker-compose -f $NEXT_DIR/docker-compose.yaml up -d \
                  -e DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
                  -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                  -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                  -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
                  -e SESSION_SECRET=${{ secrets.SESSION_SECRET }}",

                "docker ps --filter name=my-app --quiet | xargs -r docker stop",
                "docker system prune -f",

                "echo \"$NEXT_DIR\" > $WORKDIR/current",
                "echo \"Switched to $NEXT_DIR\""
            ]}'
