name: Deploy to EC2 via SSM

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application via SSM
        id: deploy_ssm
        run: |
          echo "::group::Starting Deployment Process"

          echo "Sending SSM command to deploy application..."
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application with docker-compose and .env file" \
            --parameters '{"commands": [
                "set -e",

                "echo \"[INFO] Setting up directories and environment...\"",

                "# Define working directories",
                "WORKDIR=/home/ubuntu/deployment",
                "BLUE_DIR=$WORKDIR/blue",
                "GREEN_DIR=$WORKDIR/green",

                "echo \"[INFO] Writing secrets to .env file...\"",
                "# Write secrets to .env file securely",
                "rm -f /home/ubuntu/.env",
                "echo \"DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}\" > /home/ubuntu/.env",
                "echo \"POSTGRES_USER=${{ secrets.POSTGRES_USER }}\" >> /home/ubuntu/.env",
                "echo \"POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\" >> /home/ubuntu/.env",
                "echo \"POSTGRES_DB=${{ secrets.POSTGRES_DB }}\" >> /home/ubuntu/.env",
                "echo \"SESSION_SECRET=${{ secrets.SESSION_SECRET }}\" >> /home/ubuntu/.env",
                "chmod 600 /home/ubuntu/.env",

                "echo \"[INFO] Determining current and next deployment directories...\"",
                "# Determine current active directory and compute the next",
                "CURRENT_DIR=$(sudo cat $WORKDIR/current 2>/dev/null || echo \"blue\")",
                "NEXT_DIR=$([ \"$CURRENT_DIR\" == \"blue\" ] && echo \"green\" || echo \"blue\")",

                "echo \"[INFO] Preparing deployment directory: $NEXT_DIR\"",
                "# Prepare the new directory",
                "mkdir -p $WORKDIR/$NEXT_DIR",
                "if ! curl -o $WORKDIR/$NEXT_DIR/docker-compose.yaml https://raw.githubusercontent.com/Hazqeel09/getdoav3/refs/heads/main/docker-compose.yaml; then",
                "  echo \"[ERROR] Failed to fetch docker-compose.yaml\" >&2",
                "  exit 1",
                "fi",

                "echo \"[INFO] Pulling Docker images...\"",
                "# Pull the latest Docker images",
                "if ! sudo docker-compose -f $WORKDIR/$NEXT_DIR/docker-compose.yaml --env-file /home/ubuntu/.env pull; then",
                "  echo \"[ERROR] Failed to pull Docker images\" >&2",
                "  exit 1",
                "fi",

                "echo \"[INFO] Starting new containers...\"",
                "# Start the new deployment",
                "if ! sudo docker-compose -f $WORKDIR/$NEXT_DIR/docker-compose.yaml --env-file /home/ubuntu/.env up -d; then",
                "  echo \"[ERROR] Failed to start new containers\" >&2",
                "  exit 1",
                "fi",

                "echo \"[INFO] Stopping old containers...\"",
                "# Stop old containers if the configuration exists in the current directory",
                "if [ -f $WORKDIR/$CURRENT_DIR/docker-compose.yaml ]; then",
                "  echo \"Stopping old containers in $CURRENT_DIR\"",
                "  sudo docker-compose -f $WORKDIR/$CURRENT_DIR/docker-compose.yaml down || echo \"[WARNING] Failed to stop old containers\"",
                "else",
                "  echo \"[INFO] No existing deployment found in $CURRENT_DIR to stop\"",
                "fi",

                "echo \"[INFO] Cleaning up unused Docker resources...\"",
                "# Clean up unused Docker resources",
                "sudo docker system prune -f -a --volumes || echo \"[WARNING] Failed to clean up unused Docker resources\"",

                "echo \"[INFO] Updating active deployment marker...\"",
                "# Update the current active directory marker",
                "echo \"$NEXT_DIR\" | sudo tee $WORKDIR/current > /dev/null",

                "echo \"[SUCCESS] Deployment complete. Active directory: $NEXT_DIR\""
            ]}' \
            --query "Command.CommandId" \
            --output text)

          echo "::endgroup::"
          echo "Command ID: $COMMAND_ID"
          echo "::set-output name=command_id::$COMMAND_ID"

      - name: Fetch Command Output
        run: |
          echo "::group::Fetching Command Output"
          aws ssm list-command-invocations \
            --command-id ${{ steps.deploy_ssm.outputs.command_id }} \
            --details \
            --output text \
            || echo "[ERROR] Failed to fetch command output. Check the SSM console for details."
          echo "::endgroup::"
