name: Deploy to EC2 via SSM

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application with docker-compose and injected environment variables" \
            --parameters '{"commands": [
                "set -e",

                "WORKDIR=/home/ubuntu/deployment",
                "BLUE_DIR=$WORKDIR/blue",
                "GREEN_DIR=$WORKDIR/green",

                "# Determine current active directory",
                "CURRENT_DIR=$(sudo cat $WORKDIR/current 2>/dev/null || echo \"blue\")",
                "NEXT_DIR=$([ \"$CURRENT_DIR\" == \"$BLUE_DIR\" ] && echo \"$GREEN_DIR\" || echo \"$BLUE_DIR\")",

                "echo \"Switching to $NEXT_DIR\"", 

                "# Prepare the new directory",
                "mkdir -p $NEXT_DIR",
                "curl -o $NEXT_DIR/docker-compose.yaml https://raw.githubusercontent.com/Hazqeel09/getdoav3/refs/heads/main/docker-compose.yaml",

                "# Pull new images",
                "sudo docker-compose -f $NEXT_DIR/docker-compose.yaml pull",

                "# Start the new deployment",
                "sudo docker-compose -f $NEXT_DIR/docker-compose.yaml up -d -e DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} -e SESSION_SECRET=${{ secrets.SESSION_SECRET }}",

                "# Stop old containers if docker-compose.yaml exists in CURRENT_DIR",
                "if [ -f $CURRENT_DIR/docker-compose.yaml ]; then",
                "  echo \"Stopping old containers in $CURRENT_DIR\"",
                "  sudo docker-compose -f $CURRENT_DIR/docker-compose.yaml down",
                "else",
                "  echo \"No existing deployment to stop in $CURRENT_DIR\"",
                "fi",

                "# Clean up unused Docker resources",
                "sudo docker system prune -f",

                "# Mark the new directory as active",
                "echo \"$NEXT_DIR\" | sudo tee $WORKDIR/current > /dev/null",

                "echo \"Deployment complete. Active directory: $NEXT_DIR\""
            ]}'
